### ISSUE TITLE
Upload index.html and related files for hosting?

### ISSUE THREAD

**Issue by snostorm** [ExchangeJS/exchangejs.github.io#2]
Hi Mark: not sure if you're just planning to upload the existing index.html right now or planning to do something more complicated (like Jekyll) right off the bat.

Once we have something in this repo I can re-assign the DNS. (I can also move what I have online now in here as the starting point.)

**Comment by MarkBennett** [comment]
Hey Sean!

The existing site is great so I'll probably just cut and paste then we can
tweak once it's working with new dates etc.

I got the sense from Roberto that he wanted it off of S3.

I'll copy the current site over this week. Do you have a zip of the S3
bucket? Otherwise I probably just scrape the site.

**Comment by redmantech** [comment]
Hey Mark, I added the files to Github https://github.com/redmantech/Exchangejs.com so you can grab them.

**Comment by MarkBennett** [comment]
We're hosted on GitHub now. Closing.
