### ISSUE TITLE
Fill 2017-18 Speaker Calendar

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#89]
We need to fill our [2017-18 Speaker calendar](https://docs.google.com/spreadsheets/d/1_FOG1K_fUbTlNvqT9hjihiXYt9AhPkZxW6tfZN858VU/edit?usp=sharing) before the start of the meetup. Doing this last year was a *huge* plus and made planning and announcing meetups much easier throughout the year.

At a minimum, we should fill two slots at each meetup to anchor our events.

When recruiting speakers consider looking at the [2016-17 speakers](https://docs.google.com/spreadsheets/d/1_FOG1K_fUbTlNvqT9hjihiXYt9AhPkZxW6tfZN858VU/edit#gid=0) for people to contact, or at other [older speakers](https://docs.google.com/spreadsheets/d/18Me7iCSza5jhsqGAx-eLckSAx9F78sU8i7K4Utq8fko/edit#gid=0).

**Comment by MarkBennett** [comment]
As discussed at last night's meeting, I've put @abramhindle in charge of this but all the @ExchangeJS/organizers should plan to step up and track down speakers.

**Comment by CAYdenberg** [comment]
Is that doc public @MarkBennett ? Can I just send it to anyone, or should I just ask people who might be interested?

**Comment by CAYdenberg** [comment]
Some topic suggestions from the member survey (for inspiration):
- audio (think we had a talk on this recently)
- testing (x3)
- Angular update (probably 2.x)
- Prepack
- more on web components
- Universal/isomorphic javascript
- live code a something/how to be a GitHub hero
- code organization on large projects
- more on tools and practices, not just frameworks

I already volunteered for a talk on (unit) testing, but there might room for another one on integration or e2e testing
Those last three I think people shy away from because they can devolve into opinion and be controversial. If we do do roundtable discussions they might be good topics.

**Comment by MarkBennett** [comment]
@CAYdenberg yup share away. We should probably post it up on Twitter, FB and everywhere else as well.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SteveReiter** [comment]
For those opinion topics I find it can be useful to flip it around, instead of 'This is how to organize code on a larger project' do something like 'These are common problems encountered with code organization on larger projects'. It makes it a little easier to present possible solutions without it devolving since the focus is more on the problems and less on the specific solutions.

**Comment by MarkBennett** [comment]
Hey @ExchangeJS/organizers. We're t-minus 1 month to the first meetup and have only filled one of our ten meetups. In particular we need more demos as we're trying to do one each month.

Over the next few days can you please go out of your way to share the calendar with anyone that you might think would be interested in talking. I realize that @abramhindle is taking the lead on this but everyone's help on this is appreciated as tracking down speakers is a lot of work!

You can find the calendar here:

https://docs.google.com/spreadsheets/d/1_FOG1K_fUbTlNvqT9hjihiXYt9AhPkZxW6tfZN858VU/edit?usp=sharing

And notes to help speakers here:

https://github.com/ExchangeJS/speakers

**Comment by SteveReiter** [comment]
@abramhindle I have someone who can present on A/B testing (John Ryalls). It's not an entirely javascript topic but quite related.

I put him in for March Beginner slot. Let me know if that there's any issues with that.

**Comment by SteveReiter** [comment]
Found a speaker for advanced topic on Nov. 2nd

Since the spreadsheet is public, they didn't want to include their email, what's the best way to keep track of them?
John Ryalls: [REDACTED]
Kestutis: [REDACTED]

**Comment by MarkBennett** [comment]
Awesome work @SteveReiter. I just added a second tab to the Exec Contacts spreadsheet and renamed it. Seems like a secure place to share speaker details as it's private and not meant for sharing already:

https://docs.google.com/spreadsheets/d/1-EkmzmvPtHg5syTqLQBg3ZRV_QLhUg3MWSH71T0btRI/edit#gid=1875852727

As this issue is public, I also took the liberty of removing the emails from your comment above.
