### ISSUE TITLE
Put together a sales pitch for potential sponsors

### ISSUE THREAD

**Issue by SteveReiter** [ExchangeJS/exchangejs.github.io#91]
We talked about possibly removing the 'Jobs' section of the intro each night and maybe even asking presenters to stop plugging their employer while presenting. If we do this, then what is the incentive for our sponsors?

I think we can definitely get funding from investopedia (my employer) but they are definitely going to ask what they get out of it. I'm sure they won't be the only potential sponsor with this question. If we have a good sales pitch we can definitely get more funding than if we come to sponsors with 'please give us money for not-pizza'.

**Comment by MarkBennett** [comment]
In the past we've laid out specific mentions for sponsors on the website, preroll slides, and a thank you during the night. We'll also be adding a YouTube mention to this mix in the fall. As the sponsorship level increases you get mentioned in more places. ~~On my phone right now but I'll link to the sponsorship package from last year which lays it out in more detail.~~ [Here's the link to last years sponsor package with details of how the mentions worked last year.](https://docs.google.com/presentation/d/12_2aRmpxVoZZcnujocWaQICOYgk_t9a0AXaAnf64OSw/edit?usp=sharing) Note these are sponsor thank yous and not jobs.

We've always separated job postings from sponsorship, though as we've started to get more job postings we probably need to start discriminating about what or if we mention these at the meetup. Sponsorship is one way to do this, but it discourages people sharing jobs throughout the year as most of the sponsorship happens in August and September. I've been with other meetups which have simply chosen to move all job postings to a mailing list or website, then mention that site during the meetup. This gives our attendees the chance to see all the jobs at once if they're interested, or not at all if they're not.

**Comment by CAYdenberg** [comment]
Correct me if I'm wrong but I _thought_ what we decided was not advertising jobs for companies that 1) don't have a presence at the meetup and 2) aren't sponsors. 

I think this applies particularly to a couple companies that we've called out every month but never have anyone there to tell us about them. In this case, what's the real gain for the audience? We can always tweet out their job posting and anyone interested can go look for themselves.

@MarkBennett what happened to the sponsorship package/slides we put together last summer? I thought you did a pretty good job there of laying out exactly what the benefits are.

**Comment by MarkBennett** [comment]
@CAYdenberg [Here's the sponsorship package from last year.](https://docs.google.com/presentation/d/12_2aRmpxVoZZcnujocWaQICOYgk_t9a0AXaAnf64OSw/edit?usp=sharing) I'm thinking that we should agree on the sponsor benefits them articulate them in this package.

**Comment by MarkBennett** [comment]
> Correct me if I'm wrong but I thought what we decided was not advertising jobs for companies that 1) don't have a presence at the meetup and 2) aren't sponsors.
> 
> I think this applies particularly to a couple companies that we've called out every month but never have anyone there to tell us about them. In this case, what's the real gain for the audience? We can always tweet out their job posting and anyone interested can go look for themselves.

I don't think this has been decided, but given the number of jobs we've got I'd like to propose we move the jobs out of the realtime meetup. I've created issue #92 for this.

To accomodate sponsors, we could start doing a sponsor message as many podcasts do. The sponsors would have a fixed time or number of words to share a short message with our members. They could use this time for whatever they wanted. This would include promoting their brand, sharing a job posting, or whatever else they wanted to say. This would require some work on our part to setup but it would make it easer for the MC because it would be a fixed message and time each month. Sponsors also wouldn't need to worry about remembering what to say.

I'd propose that this sponsor message be at the end of the meetup when ours thank yous take place, and only apply to the two sponsors with the highest sponsorship level.

Thoughts?

**Comment by MarkBennett** [comment]
@SteveReiter thanks for setting this up btw. Want me to make a 2017-18 copy of the sponsorship package we can hack on?

**Comment by SteveReiter** [comment]
Ya we might as well update it. Doesn't look like it needs a lot of changes.

**Comment by MarkBennett** [comment]
Here's a copy for 2017-18:

https://docs.google.com/presentation/d/1kIfoh0mcqmi6cWQtL3zWo03Oc9yfh9CsywKT8NQPAU0/edit?usp=sharing

**Comment by MarkBennett** [comment]
Hey @SteveReiter. One thing I'd like to do differently than last year, is ship an onboarding sign up form with the sponsorship pack. I had to on-board each sponsor manually last year which took a while, but now that we have a good sense of what we need we could probably wrap it up in a little form that they could submit through the website.

Based off of last year, I think we'd want to know..

1) Company name
2) Sponsorship level
3) Description of company
4) Name and email of company contact
5) Special sponsorship considerations (if any)
6) A short 30 second blurb we'd share with members at each meetup (top level sponsorship only)
7) A small logo image for the website
8) A full screen size logo we can use for our presentations and slides

There's probably more which isn't coming to me now. I wish Github let you save draft comments!

**Comment by SteveReiter** [comment]
Looks like we need to resolve the following to get the ball rolling:
1) https://www.exchangejs.com/sponsorship is a 404, did we have this page up in the past? Does it need to be replaced or should we remove the link?
2) The Partner sponsorship level is a bit vague and/or the parts of the site mentioned don't exist, where are we at with that?

**Comment by MarkBennett** [comment]
The link is new, but we should probably get it live seeing how I added it to the sponsorship package already. ;)

It could just redirect to that survey and we could setup an addon to email us when someone submits it. I'll add an issue to do this and mark it urgent so it doesn't slip through the cracks.

**Comment by MarkBennett** [comment]
There are three places we propose giving a sponsor coverage right now:

1) A specific mention and a full slide during the thank yous at the meetup
2) A non-specific thank you on a shared partner slide at the meetup
3) A mention on the community section of the website

Champions ($2000+) have gotten 1 and 3, Partners ($1000+) get 2 and 3, and Supporters ($500+) get just 3. Last year we just had Jobber and Clio as sponsors, both at the champion level so they get mentions at each meetup and in the sponsor section on the homepage of the website. We also acknowledge Startup Edmonton as we calculate the value of the space they provide each month to be in excess of $2000.

Going forward, I propose we keep a similar structure, but with a few small changes. It could look like this:

1) A 30-second message and accompanying slide delivered at each meetup. (Content delivered and agreed to by exec.)
2) An exclusive slide of your logo during the thank yous at each meetup.
3) A logo on a shared partner slide during the thank yous at each meetup (specific names wouldn't be mentioned.)
4) A logo on the community section of the website.

Champions would get 1, 2, and 4. Partners would get 3 and 4. Supporters would get 4.

I think these benefits are clearer and more specific. I also really like delivering a tight and rehearsed message from sponsors. This would give sponsors a chance to be sure they're getting out the right message, but also give us a chance to control meetup length. As well, since the jobs are moving to the website this would give us a chance to further tighten the evenings schedule.

Thoughts? See any tweaks to make this more palatable to members and sponsors? I'm kind of thinking about how some of the podcasts I enjoy do their sponsor messages. 99% Invisible for example does a really cool thing where their sponsor messages are all at the back end of the show. We could do something similar.

_UPDATED TO FIX SOME TYPOS_

**Comment by MarkBennett** [comment]
I just updated slides to show how we might present these to the sponsors.

![docs google com-presentation-d-1kifoh0mcqmi6cwqtl3zwo03oc9yfh9csywkt8nqpau0-pub-start false loop false delayms 10000 slide id g53387496f38a523_1](https://user-images.githubusercontent.com/61872/29443079-e57e4fb6-8392-11e7-97b6-fd91020bae49.png)


https://docs.google.com/presentation/d/1kIfoh0mcqmi6cWQtL3zWo03Oc9yfh9CsywKT8NQPAU0/pub?start=false&loop=false&delayms=10000&slide=id.g53387496f38a523_1

**Comment by MarkBennett** [comment]
The [https://exchangejs.com/sponsorship](https://exchangejs.com/sponsorshiphttps://exchangejs.com/sponsorship) link works now. ;)

**Comment by MarkBennett** [comment]
@SteveReiter thoughts on these proposed sponsorship levels and associated compensation?

**Comment by SteveReiter** [comment]
Looks good to me!

**Comment by MarkBennett** [comment]
This is done for now. Closing.
